import React from "react";
import CategoryPromoSection from "./CategoryPromoSection";
import productImg from "../../../assets/products/laptop.jpg";

import mobileBanner from "../../../assets/promo-section/mobile-banner.png"
import laptopBanner from "../../../assets/promo-section/laptop-banner.png"

import cellPhoneSmallImg from "../../../assets/promo-section/iphone.png"
import mackBookSmallImg from "../../../assets/promo-section/mackbook.png"


const cellphonesSection = {
    title: "Top Cellphones & Tablets",
    bannerImage: mobileBanner,
    bannerHeading: "Redmi Note 12 Pro+ 5G",
    bannerSubtext: "Rise to the challenge",
    bannerCta: "Shop now",
    bannerVariant: "light",
    subcategories: [
        { image: cellPhoneSmallImg, name: "iPhone (iOS)", itemCount: 74 },
        { image: cellPhoneSmallImg, name: "Android", itemCount: 35 },
        { image: cellPhoneSmallImg, name: "5G Support", itemCount: 12 },
        { image: cellPhoneSmallImg, name: "Gaming", itemCount: 9 },
        { image: cellPhoneSmallImg, name: "Xiaomi", itemCount: 52 },
        { image: cellPhoneSmallImg, name: "Accessories", itemCount: 28 },
    ],
    products: [
        {
            reviews: 152,
            title: "BOSO 2 Wireless On Ear Headphone",
            price: 359.0,
            rating: 3.5,
            oldPrice: null,
            save: null,
            tags: ["Free Shipping", "Free Gift"],
            stock: "in",
            thumbnail: productImg,
            categoryTags: ["best-seller"],
            wishlist: true,
            addToCard: false,
        },
        {
            reviews: 152,
            title: "OPod Pro 12.9 Inch M1 2023, 64GB + Wifi, GPS",
            price: 569.0,
            rating: 4,
            oldPrice: 759.0,
            save: 199.0,
            tags: ["Free Shipping"],
            stock: "in",
            thumbnail: productImg,
            categoryTags: ["best-seller", "popular"],
            wishlist: true,
            addToCard: true,
        },
        {
            reviews: 8,
            title: "uLosk Mini case 2.0, Xenon i10 / 32GB / SSD 512GB / VGA 8GB",
            price: 1729.0,
            rating: 5,
            oldPrice: 1799.0,
            save: 59.0,
            tags: ["Free Shipping"],
            stock: "out",
            thumbnail: productImg,
            categoryTags: ["best-seller"],
            wishlist: true,
            addToCard: false,
        },
        {
            reviews: null,
            title: "Oppto Watch Series 8 GPS + Cellular Stainless Steel Case with Milanese Loop",
            price: 9.0,
            rating: 3.5,
            oldPrice: null,
            save: null,
            tags: ["$2.99 Shipping"],
            stock: "preorder",
            thumbnail: productImg,
            categoryTags: ["best-seller", "new-in"],
            wishlist: false,
            addToCard: false,
        },
        {
            reviews: 21,
            title: "Vexa Smart Air Fryer 6.5L Digital Touchscreen",
            price: 89.0,
            rating: 4.5,
            oldPrice: 119.0,
            save: 30.0,
            tags: ["Free Shipping"],
            stock: "in",
            thumbnail: productImg,
            categoryTags: ["new-in"],
            wishlist: true,
            addToCard: false,
        },
        {
            reviews: 4,
            title: "Norra Mechanical Keyboard 75% Hot-Swap RGB",
            price: 79.0,
            rating: 4,
            oldPrice: null,
            save: null,
            tags: ["Free Gift"],
            stock: "in",
            thumbnail: productImg,
            categoryTags: ["new-in"],
            wishlist: true,
            addToCard: false,
        },
        {
            reviews: 13,
            title: "Plyno 4K Action Camera with Waterproof Case",
            price: 149.0,
            rating: 3.5,
            oldPrice: 189.0,
            save: 40.0,
            tags: ["Free Shipping"],
            stock: "in",
            thumbnail: productImg,
            categoryTags: ["new-in", "popular"],
            wishlist: false,
            addToCard: true,
        },
        {
            reviews: null,
            title: "Hexel Smart Door Lock with Fingerprint + App",
            price: 129.0,
            rating: 4,
            oldPrice: null,
            save: null,
            tags: ["$4.99 Shipping"],
            stock: "preorder",
            thumbnail: productImg,
            categoryTags: ["new-in"],
            wishlist: true,
            addToCard: false,
        },
        {
            reviews: 312,
            title: "Bravo Insulated Water Bottle 1L Stainless Steel",
            price: 24.0,
            rating: 5,
            oldPrice: 32.0,
            save: 8.0,
            tags: ["Free Shipping"],
            stock: "in",
            thumbnail: productImg,
            categoryTags: ["popular"],
            wishlist: true,
            addToCard: false,
        },
        {
            reviews: 88,
            title: "Quira Wireless Charging Pad 3-in-1 Stand",
            price: 39.0,
            rating: 4.5,
            oldPrice: null,
            save: null,
            tags: ["Free Gift"],
            stock: "in",
            thumbnail: productImg,
            categoryTags: ["popular"],
            wishlist: true,
            addToCard: false,
        },
        {
            reviews: 6,
            title: "Fenro Desk Lamp with Wireless Charger Base",
            price: 45.0,
            rating: 4,
            oldPrice: 59.0,
            save: 14.0,
            tags: ["Free Shipping"],
            stock: "out",
            thumbnail: productImg,
            categoryTags: ["popular"],
            wishlist: false,
            addToCard: true,
        },
        {
            reviews: 47,
            title: "Liso Ceramic Cookware Set 10-Piece",
            price: 199.0,
            rating: 4.5,
            oldPrice: null,
            save: null,
            tags: ["$5.99 Shipping"],
            stock: "in",
            thumbnail: productImg,
            categoryTags: ["popular"],
            wishlist: false,
            addToCard: true,
        },
    ]
};

const laptopsSection = {
    title: "Best Laptops & Computers",
    bannerImage: laptopBanner,
    bannerHeading: "Mobok 2 Superchard",
    bannerSubtext: "By M2 — Start from $1199",
    bannerCta: "Shop now",
    bannerVariant: "dark",
    subcategories: [
        { image: mackBookSmallImg, name: "Macbook", itemCount: 74 },
        { image: mackBookSmallImg, name: "Gaming PC", itemCount: 5 },
        { image: mackBookSmallImg, name: "Laptop Office", itemCount: 22 },
        { image: mackBookSmallImg, name: 'Laptop 15"', itemCount: 55 },
        { image: mackBookSmallImg, name: "M1 2023", itemCount: 32 },
        { image: mackBookSmallImg, name: "Secondhand", itemCount: 18 },
    ],
    products: [
        {
            reviews: 152,
            title: "BOSO 2 Wireless On Ear Headphone",
            price: 359.0,
            rating: 3.5,
            oldPrice: null,
            save: null,
            tags: ["Free Shipping", "Free Gift"],
            stock: "in",
            thumbnail: productImg,
            categoryTags: ["best-seller"],
            wishlist: true,
            addToCard: false,
        },
        {
            reviews: 152,
            title: "OPod Pro 12.9 Inch M1 2023, 64GB + Wifi, GPS",
            price: 569.0,
            rating: 4,
            oldPrice: 759.0,
            save: 199.0,
            tags: ["Free Shipping"],
            stock: "in",
            thumbnail: productImg,
            categoryTags: ["best-seller", "popular"],
            wishlist: true,
            addToCard: true,
        },
        {
            reviews: 8,
            title: "uLosk Mini case 2.0, Xenon i10 / 32GB / SSD 512GB / VGA 8GB",
            price: 1729.0,
            rating: 5,
            oldPrice: 1799.0,
            save: 59.0,
            tags: ["Free Shipping"],
            stock: "out",
            thumbnail: productImg,
            categoryTags: ["best-seller"],
            wishlist: true,
            addToCard: false,
        },
        {
            reviews: null,
            title: "Oppto Watch Series 8 GPS + Cellular Stainless Steel Case with Milanese Loop",
            price: 9.0,
            rating: 3.5,
            oldPrice: null,
            save: null,
            tags: ["$2.99 Shipping"],
            stock: "preorder",
            thumbnail: productImg,
            categoryTags: ["best-seller", "new-in"],
            wishlist: false,
            addToCard: false,
        },
        {
            reviews: 21,
            title: "Vexa Smart Air Fryer 6.5L Digital Touchscreen",
            price: 89.0,
            rating: 4.5,
            oldPrice: 119.0,
            save: 30.0,
            tags: ["Free Shipping"],
            stock: "in",
            thumbnail: productImg,
            categoryTags: ["new-in"],
            wishlist: true,
            addToCard: false,
        },
        {
            reviews: 4,
            title: "Norra Mechanical Keyboard 75% Hot-Swap RGB",
            price: 79.0,
            rating: 4,
            oldPrice: null,
            save: null,
            tags: ["Free Gift"],
            stock: "in",
            thumbnail: productImg,
            categoryTags: ["new-in"],
            wishlist: true,
            addToCard: false,
        },
        {
            reviews: 13,
            title: "Plyno 4K Action Camera with Waterproof Case",
            price: 149.0,
            rating: 3.5,
            oldPrice: 189.0,
            save: 40.0,
            tags: ["Free Shipping"],
            stock: "in",
            thumbnail: productImg,
            categoryTags: ["new-in", "popular"],
            wishlist: false,
            addToCard: true,
        },
        {
            reviews: null,
            title: "Hexel Smart Door Lock with Fingerprint + App",
            price: 129.0,
            rating: 4,
            oldPrice: null,
            save: null,
            tags: ["$4.99 Shipping"],
            stock: "preorder",
            thumbnail: productImg,
            categoryTags: ["new-in"],
            wishlist: true,
            addToCard: false,
        },
        {
            reviews: 312,
            title: "Bravo Insulated Water Bottle 1L Stainless Steel",
            price: 24.0,
            rating: 5,
            oldPrice: 32.0,
            save: 8.0,
            tags: ["Free Shipping"],
            stock: "in",
            thumbnail: productImg,
            categoryTags: ["popular"],
            wishlist: true,
            addToCard: false,
        },
        {
            reviews: 88,
            title: "Quira Wireless Charging Pad 3-in-1 Stand",
            price: 39.0,
            rating: 4.5,
            oldPrice: null,
            save: null,
            tags: ["Free Gift"],
            stock: "in",
            thumbnail: productImg,
            categoryTags: ["popular"],
            wishlist: true,
            addToCard: false,
        },
        {
            reviews: 6,
            title: "Fenro Desk Lamp with Wireless Charger Base",
            price: 45.0,
            rating: 4,
            oldPrice: 59.0,
            save: 14.0,
            tags: ["Free Shipping"],
            stock: "out",
            thumbnail: productImg,
            categoryTags: ["popular"],
            wishlist: false,
            addToCard: true,
        },
        {
            reviews: 47,
            title: "Liso Ceramic Cookware Set 10-Piece",
            price: 199.0,
            rating: 4.5,
            oldPrice: null,
            save: null,
            tags: ["$5.99 Shipping"],
            stock: "in",
            thumbnail: productImg,
            categoryTags: ["popular"],
            wishlist: false,
            addToCard: true,
        },
    ]
};

export default function CategoryPromoSections() {
    return (
        <div className="container mx-auto flex w-full max-w-7xl flex-col gap-4">
            <CategoryPromoSection {...cellphonesSection} />
            <CategoryPromoSection {...laptopsSection} />
        </div>
    );
}